### ISSUE TITLE
CMake build is missing gfn0-config.cmake

### ISSUE THREAD

**Issue by sheepforce** [pprcht/gfn0#1]
The gfn0 package can't be found by CMake's `find_package` mechanism as the `gfn0-config.cmake` file is missing in the installation. This is probably the same issue as in https://github.com/grimme-lab/numsa/issues/11

**Comment by pprcht** [comment]
I've added an install for the gfn0-config.cmake file similar as the numsa project does it. Same for pprcht/gfnff#1

I'm not fully satisfied with the LAPACK handling in these projects though, might revise this at a later time.

**Comment by sheepforce** [comment]
Thank you very much! :)

I've got a step further in building Crest, ultimately. I'm not really a CMake expert, but have two other remarks:

  * The installation prefix can end up doubled in `gfn0-targets.cmake`, e.g. `INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}//usr/local/include" if `CMAKE_INSTALL_INCLUDEDIR` is specified and an absolute path.
  * CREST now finds both projects, but complains about missing mod files for these two projects. I don't know if this problem lives in these cmake files or in CREST's, though.
  ```
crest> [ 37%] Building Fortran object CMakeFiles/crest-exe.dir/src/legacy_algos/zsort.f90.o
crest> /build/source/src/calculator/gfn0_api.F90:29:7:
crest> 
crest>    29 |   use gfn0_interface
crest>       |       1
crest> Fatal Error: Cannot open module file 'gfn0_interface.mod' for reading at (1): No such file or directory
crest> compilation terminated.
crest> make[2]: *** [CMakeFiles/crest-exe.dir/build.make:374: CMakeFiles/crest-exe.dir/src/calculator/gfn0_api.F90.o] Error 1
crest> make[2]: *** Waiting for unfinished jobs....
crest> /build/source/src/calculator/gfnff_api.F90:29:7:
crest> 
crest>    29 |   use gfnff_interface
crest>       |       1
crest> Fatal Error: Cannot open module file 'gfnff_interface.mod' for reading at (1): No such file or directory
crest> compilation terminated.
crest> make[2]: *** [CMakeFiles/crest-exe.dir/build.make:387: CMakeFiles/crest-exe.dir/src/calculator/gfnff_api.F90.o] Error 1
crest> make[1]: *** [CMakeFiles/Makefile2:331: CMakeFiles/crest-exe.dir/all] Error 2
crest> make: *** [Makefile:136: all] Error 2
  ```

**Comment by pprcht** [comment]
Pretty sure it lives in crest, the CMake build there is long overdue for an overhaul. I might just try to do that.

I usually download the repositories via the `git submodule` structure within crest so that gfn0/gfnff source doesn't live globally in the first place. Might also be the reason why there wasn't a complaint about the missing `gfn0-config.cmake` so far.

Anyways, thanks for kicking that off.

**Comment by sheepforce** [comment]
> Pretty sure it lives in crest, the CMake build there is long overdue for an overhaul. I might just try to do that.

Oh I would very much appreciate this :blush: 

> I usually download the repositories via the git submodule structure within crest so that gfn0/gfnff source doesn't live globally in the first place.

Hm yes, this was more or less my workaround, manually copying the sources in. I'm building the Nix packages and they are run in a very isolated sandbox with checks for all Hashes. For packaging a correct dependency resolution would be much nicer than building each and everything in place over and over again, especially if patches are required for the packaging. :)

For the moment should we close this issue?

**Comment by pprcht** [comment]
> For the moment should we close this issue?

sure
